lib/movie_space_web/router.ex
defmodule MovieSpaceWeb.Router do
  use MovieSpaceWeb, :router
  use Pow.Phoenix.Router
  use PowAssent.Phoenix.Router
  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MovieSpaceWeb.LayoutView, :root}
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :skip_csrf_protection do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  scope "/" do
    pipe_through :skip_csrf_protection

    pow_assent_authorization_post_callback_routes()
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()
    pow_assent_routes()
  end

  scope "/", MovieSpaceWeb do
    pipe_through [:browser, :protected]

    resources "/", MovieController, only: [:index, :show, :new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", MovieSpaceWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MovieSpaceWeb.Telemetry
    end
  end
end

lib/movie_space_web/views/layout_view.ex
defmodule MovieSpaceWeb.LayoutView do
  use MovieSpaceWeb, :view
end

lib/movie_space_web/templates/layout/app.html.eex
<main role="main" class="container">
  <%= @inner_content %>
</main>

lib/movie_space_web/templates/layout/navbar.html.eex
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link "Movie Space", class: "navbar-brand", to: Routes.movie_path(@conn, :index) %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <%= if Pow.Plug.current_user(@conn) do %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @current_user.email %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link "New Movie", to: Routes.movie_path(@conn, :new) %></li>
            <li><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li class="active">
          <%= link "Sign in", to: Routes.pow_session_path(@conn, :new) %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>